<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="15.0">
  <!-- The .csrpoj file uses ../Directory.Build.props as a source for some configurations -->
  <PropertyGroup>
    <AssemblyName>itext.styledxmlparser.tests</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\itext\itext.pdftest\itext.pdftest.csproj" />
    <ProjectReference Include="..\..\itext\itext.styledxmlparser\itext.styledxmlparser.csproj" />
  </ItemGroup>
</Project>