/*
This file is part of the iText (R) project.
Copyright (c) 1998-2024 Apryse Group NV
Authors: Apryse Software.

This program is offered under a commercial and under the AGPL license.
For commercial licensing, contact us at https://itextpdf.com/sales.  For AGPL licensing, see below.

AGPL licensing:
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/
using System;
using iText.Svg.Renderers;
using iText.Test;

namespace iText.Svg.Jfreesvg {
    [NUnit.Framework.Category("IntegrationTest")]
    public class JFreeSvgTest : SvgIntegrationTest {
        private static readonly String SOURCE_FOLDER = iText.Test.TestUtil.GetParentProjectDirectory(NUnit.Framework.TestContext
            .CurrentContext.TestDirectory) + "/resources/itext/svg/JFreeSvgTest/";

        private static readonly String DESTINATION_FOLDER = NUnit.Framework.TestContext.CurrentContext.TestDirectory
             + "/test/itext/svg/JFreeSvgTest/";

        [NUnit.Framework.OneTimeSetUp]
        public static void BeforeClass() {
            ITextTest.CreateDestinationFolder(DESTINATION_FOLDER);
        }

        //Do not make changes in svg file because it was generated by JFreeSVG
        [NUnit.Framework.Test]
        public virtual void UsingJFreeSvgFromStringTest() {
            ConvertAndCompare(SOURCE_FOLDER, DESTINATION_FOLDER, "rectangleFromStringTest");
        }

        //Do not make changes in svg file because it was generated by JFreeSVG
        [NUnit.Framework.Test]
        public virtual void UsingJFreeSvgFromFileTest() {
            ConvertAndCompare(SOURCE_FOLDER, DESTINATION_FOLDER, "rectangleFromFileTest");
        }

        //Do not make changes in svg file because it was generated by JFreeSVG
        [NUnit.Framework.Test]
        public virtual void PieChartByJFreeSvgTest() {
            ConvertAndCompare(SOURCE_FOLDER, DESTINATION_FOLDER, "usingJFreeSvgPieChartFromFileTest");
        }

        //Do not make changes in svg file because it was generated by JFreeSVG
        [NUnit.Framework.Test]
        public virtual void BarChartByJFreeSvgFromStringTest() {
            //TODO: update cmp file when DEVSIX-4043 will be fixed
            ConvertAndCompare(SOURCE_FOLDER, DESTINATION_FOLDER, "usingJFreeSvgBarChartFromStringTest");
        }

        //Do not make changes in svg file because it was generated by JFreeSVG
        [NUnit.Framework.Test]
        public virtual void BarChartByJFreeSvgFromFileTest() {
            //TODO: update cmp file when DEVSIX-4043 will be fixed
            ConvertAndCompare(SOURCE_FOLDER, DESTINATION_FOLDER, "usingJFreeSvgBarChartFromFileTest");
        }

        //Do not make changes in svg file because it was generated by JFreeSVG
        [NUnit.Framework.Test]
        public virtual void LineChartByJFreeSvgFromStringTest() {
            ConvertAndCompare(SOURCE_FOLDER, DESTINATION_FOLDER, "usingJFreeSvgLineChartFromStringTest");
        }

        //Do not make changes in svg file because it was generated by JFreeSVG
        [NUnit.Framework.Test]
        public virtual void LineChartByJFreeSvgFromFileTest() {
            ConvertAndCompare(SOURCE_FOLDER, DESTINATION_FOLDER, "usingJFreeSvgLineChartFromFileTest");
        }

        //Do not make changes in svg file because it was generated by JFreeSVG
        [NUnit.Framework.Test]
        public virtual void XyChartByJFreeSvgFromStringTest() {
            ConvertAndCompare(SOURCE_FOLDER, DESTINATION_FOLDER, "usingJFreeSvgXYChartFromStringTest");
        }

        //Do not make changes in svg file because it was generated by JFreeSVG
        [NUnit.Framework.Test]
        public virtual void XyChartByJFreeSvgFromFileTest() {
            ConvertAndCompare(SOURCE_FOLDER, DESTINATION_FOLDER, "usingJFreeSvgXYChartFromFileTest");
        }
    }
}
