using System;
using iText.Svg.Exceptions;
using iText.Svg.Renderers;
using iText.Test;
using iText.Test.Attributes;

namespace iText.Svg.Jfreesvg {
    public class JFreeSvg : SvgIntegrationTest {
        private static readonly String SOURCE_FOLDER = iText.Test.TestUtil.GetParentProjectDirectory(NUnit.Framework.TestContext
            .CurrentContext.TestDirectory) + "/resources/itext/svg/JFreeSvg/";

        private static readonly String DESTINATION_FOLDER = iText.Test.TestUtil.GetParentProjectDirectory(NUnit.Framework.TestContext
            .CurrentContext.TestDirectory) + "/resources/itext/svg/JFreeSvg/";

        [NUnit.Framework.OneTimeSetUp]
        public static void BeforeClass() {
            ITextTest.CreateDestinationFolder(DESTINATION_FOLDER);
        }

        //Do not make changes in svg file because it was generated by JFreeSVG
        /// <exception cref="System.IO.IOException"/>
        /// <exception cref="System.Exception"/>
        [NUnit.Framework.Test]
        public virtual void UsingJFreeSvgFromString() {
            //TODO: update cmp_ when RND-1029 fixed
            ConvertAndCompareVisually(SOURCE_FOLDER, DESTINATION_FOLDER, "rectangleFromString");
        }

        //Do not make changes in svg file because it was generated by JFreeSVG
        /// <exception cref="System.IO.IOException"/>
        /// <exception cref="System.Exception"/>
        [NUnit.Framework.Test]
        public virtual void UsingJFreeSvgFromFile() {
            //TODO: update cmp_ when RND-1029 fixed
            ConvertAndCompareVisually(SOURCE_FOLDER, DESTINATION_FOLDER, "rectangleFromFile");
        }

        //Do not make changes in svg file because it was generated by JFreeSVG
        /// <exception cref="System.IO.IOException"/>
        /// <exception cref="System.Exception"/>
        [NUnit.Framework.Test]
        public virtual void PieChartByJFreeSvg() {
            ConvertAndCompareVisually(SOURCE_FOLDER, DESTINATION_FOLDER, "usingJFreeSvgPieChartFromFile");
        }

        //Do not make changes in svg file because it was generated by JFreeSVG
        /// <exception cref="System.IO.IOException"/>
        /// <exception cref="System.Exception"/>
        [NUnit.Framework.Test]
        [LogMessage(SvgLogMessageConstant.UNMAPPEDTAG, Count = 80)]
        public virtual void BarChartByJFreeSvgFromString() {
            // TODO: Update cmp_ file when DEVSIX-2086 resolved
            ConvertAndCompareVisually(SOURCE_FOLDER, DESTINATION_FOLDER, "usingJFreeSvgBarChartFromString");
        }

        //Do not make changes in svg file because it was generated by JFreeSVG
        /// <exception cref="System.IO.IOException"/>
        /// <exception cref="System.Exception"/>
        [NUnit.Framework.Test]
        [LogMessage(SvgLogMessageConstant.UNMAPPEDTAG, Count = 80)]
        public virtual void BarChartByJFreeSvgFromFile() {
            // TODO: Update cmp_ file when DEVSIX-2086 resolved
            ConvertAndCompareVisually(SOURCE_FOLDER, DESTINATION_FOLDER, "usingJFreeSvgBarChartFromFile");
        }

        //Do not make changes in svg file because it was generated by JFreeSVG
        /// <exception cref="System.IO.IOException"/>
        /// <exception cref="System.Exception"/>
        [NUnit.Framework.Test]
        public virtual void LineChartByJFreeSvgFromString() {
            ConvertAndCompareVisually(SOURCE_FOLDER, DESTINATION_FOLDER, "usingJFreeSvgLineChartFromString");
        }

        //Do not make changes in svg file because it was generated by JFreeSVG
        /// <exception cref="System.IO.IOException"/>
        /// <exception cref="System.Exception"/>
        [NUnit.Framework.Test]
        public virtual void LineChartByJFreeSvgFromFile() {
            ConvertAndCompareVisually(SOURCE_FOLDER, DESTINATION_FOLDER, "usingJFreeSvgLineChartFromFile");
        }

        //Do not make changes in svg file because it was generated by JFreeSVG
        /// <exception cref="System.IO.IOException"/>
        /// <exception cref="System.Exception"/>
        [NUnit.Framework.Test]
        public virtual void XyChartByJFreeSvgFromString() {
            ConvertAndCompareVisually(SOURCE_FOLDER, DESTINATION_FOLDER, "usingJFreeSvgXYChartFromString");
        }

        //Do not make changes in svg file because it was generated by JFreeSVG
        /// <exception cref="System.IO.IOException"/>
        /// <exception cref="System.Exception"/>
        [NUnit.Framework.Test]
        public virtual void XyChartByJFreeSvgFromFile() {
            ConvertAndCompareVisually(SOURCE_FOLDER, DESTINATION_FOLDER, "usingJFreeSvgXYChartFromFile");
        }
    }
}
