<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="15.0">
  <!-- The .csrpoj file uses ../Directory.Build.props as a source for some configurations -->
  <PropertyGroup>
    <AssemblyName>itext.forms.tests</AssemblyName>
  </PropertyGroup>
 <ItemGroup>
    <ProjectReference Include="..\..\itext\itext.forms\itext.forms.csproj" />
    <ProjectReference Include="..\..\itext\itext.pdftest\itext.pdftest.csproj" />
    <ProjectReference Include="..\..\itext\itext.font-asian\itext.font-asian.csproj" />
    <ProjectReference Include="..\..\itext\itext.bouncy-castle-adapter\itext.bouncy-castle-adapter.csproj" />
    <ProjectReference Include="..\..\itext\itext.bouncy-castle-fips-adapter\itext.bouncy-castle-fips-adapter.csproj" />
  </ItemGroup>
</Project>