<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="15.0">
  <!-- The .csrpoj file uses ../Directory.Build.props as a source for some configurations -->
  <PropertyGroup>
    <AssemblyName>itext.pdftest</AssemblyName>
  </PropertyGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' ">
    <PackageReference Include="System.Collections.Concurrent" Version="4.3.0" />
    <PackageReference Include="System.Reflection.Extensions" Version="4.3.0" />
    <!--    
     Explicitly add System.Net.Http v4.3.4 dependency.
     Without this explicit dependency Rider IDE somehow cannot properly resolve it, which ends up in FileNotFound exception
     in code that executes UrlUtil#OpenStream.
    -->
    <PackageReference Include="System.Net.Http" Version="4.3.4" />
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'net461' ">
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Xml" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="BouncyCastle.Cryptography" Version="2.6.2" />
    <PackageReference Include="NUnit" Version="3.7.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\itext.io\itext.io.csproj" />
  </ItemGroup>
  <ItemGroup>
	<Content Include="lib\verapdf\VeraPDF_license.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <None Include="packages.config" />
    <None Update="lib\verapdf\VeraPdfValidatorApp.jar">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>