<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="15.0">
  <!-- The .csrpoj file uses ../Directory.Build.props as a source for some configurations -->
  <PropertyGroup>
    <AssemblyName>itext.commons.tests</AssemblyName>
    <LangVersion>9.0</LangVersion>
  </PropertyGroup>
  <PropertyGroup>
    <!-- NoWarn property from ../Directory.Build.props is overriden -->
    <NoWarn>$(NoWarn);1903</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\itext\itext.commons\itext.commons.csproj" />
    <ProjectReference Include="..\..\itext\itext.pdftest\itext.pdftest.csproj" />
  </ItemGroup>
</Project>