<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="15.0">
  <!-- The .csrpoj file uses ../Directory.Build.props as a source for some configurations -->
  <PropertyGroup>
    <AssemblyName>itext.pdfa.tests</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\itext\itext.barcodes\itext.barcodes.csproj" />
    <ProjectReference Include="..\..\itext\itext.pdfa\itext.pdfa.csproj" />
    <ProjectReference Include="..\..\itext\itext.pdftest\itext.pdftest.csproj" />
    <ProjectReference Include="..\..\itext\itext.forms\itext.forms.csproj" />
  </ItemGroup>
  <ItemGroup>
  </ItemGroup>
</Project>