<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="15.0">
  <!-- The .csrpoj file uses ../Directory.Build.props as a source for some configurations -->
  <PropertyGroup>
    <AssemblyName>itext.io.tests</AssemblyName>
  </PropertyGroup>
 <ItemGroup>
    <ProjectReference Include="..\..\itext\itext.io\itext.io.csproj" />
    <ProjectReference Include="..\..\itext\itext.pdftest\itext.pdftest.csproj" />
    <ProjectReference Include="..\..\itext\itext.font-asian\itext.font-asian.csproj" />
  </ItemGroup>
</Project>