// <auto-generated/>
#if NETSTANDARD2_0

#nullable enable annotations
#nullable disable warnings

// Suppress warnings about [Obsolete] member usage in generated code.
#pragma warning disable CS0612, CS0618

namespace iText.Commons.Utils
{
    public partial class ClassWithDefaultValueContext
    {
        private static readonly global::System.Text.Json.JsonEncodedText PropName_firstString = global::System.Text.Json.JsonEncodedText.Encode("firstString");
        private static readonly global::System.Text.Json.JsonEncodedText PropName_integer = global::System.Text.Json.JsonEncodedText.Encode("integer");
        private static readonly global::System.Text.Json.JsonEncodedText PropName_doubleValue = global::System.Text.Json.JsonEncodedText.Encode("doubleValue");
    }
}
#endif