/*
    This file is part of the iText (R) project.
    Copyright (c) 1998-2025 Apryse Group NV
    Authors: Apryse Software.

    This program is offered under a commercial and under the AGPL license.
    For commercial licensing, contact us at https://itextpdf.com/sales.  For AGPL licensing, see below.

    AGPL licensing:
    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
﻿// <auto-generated/>
#if NETSTANDARD2_0

#nullable enable annotations
#nullable disable warnings

// Suppress warnings about [Obsolete] member usage in generated code.
#pragma warning disable CS0612, CS0618

namespace iText.Commons.Utils
{
    public partial class ComplexStructureContext
    {
        private static readonly global::System.Text.Json.JsonEncodedText PropName_arrayStr = global::System.Text.Json.JsonEncodedText.Encode("arrayStr");
        private static readonly global::System.Text.Json.JsonEncodedText PropName_grandsons = global::System.Text.Json.JsonEncodedText.Encode("grandsons");
        private static readonly global::System.Text.Json.JsonEncodedText PropName_map = global::System.Text.Json.JsonEncodedText.Encode("map");
        private static readonly global::System.Text.Json.JsonEncodedText PropName_str = global::System.Text.Json.JsonEncodedText.Encode("str");
        private static readonly global::System.Text.Json.JsonEncodedText PropName_childsMap = global::System.Text.Json.JsonEncodedText.Encode("childsMap");
        private static readonly global::System.Text.Json.JsonEncodedText PropName_integer = global::System.Text.Json.JsonEncodedText.Encode("integer");
        private static readonly global::System.Text.Json.JsonEncodedText PropName_name = global::System.Text.Json.JsonEncodedText.Encode("name");
    }
}
#endif