// <auto-generated/>
#if NETSTANDARD2_0

#nullable enable annotations
#nullable disable warnings

// Suppress warnings about [Obsolete] member usage in generated code.
#pragma warning disable CS0612, CS0618

namespace iText.Commons.Utils
{
    public partial class ComplexStructureContext
    {
        private static readonly global::System.Text.Json.JsonEncodedText PropName_arrayStr = global::System.Text.Json.JsonEncodedText.Encode("arrayStr");
        private static readonly global::System.Text.Json.JsonEncodedText PropName_grandsons = global::System.Text.Json.JsonEncodedText.Encode("grandsons");
        private static readonly global::System.Text.Json.JsonEncodedText PropName_map = global::System.Text.Json.JsonEncodedText.Encode("map");
        private static readonly global::System.Text.Json.JsonEncodedText PropName_str = global::System.Text.Json.JsonEncodedText.Encode("str");
        private static readonly global::System.Text.Json.JsonEncodedText PropName_childsMap = global::System.Text.Json.JsonEncodedText.Encode("childsMap");
        private static readonly global::System.Text.Json.JsonEncodedText PropName_integer = global::System.Text.Json.JsonEncodedText.Encode("integer");
        private static readonly global::System.Text.Json.JsonEncodedText PropName_name = global::System.Text.Json.JsonEncodedText.Encode("name");
    }
}
#endif