<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="15.0">
  <!-- The .csrpoj file uses ../Directory.Build.props as a source for some configurations -->
  <PropertyGroup>
    <!-- TargetFrameworks property from ../Directory.Build.props is overriden -->
    <TargetFrameworks>netstandard2.0</TargetFrameworks>
    <AssemblyName>itext.bouncy-castle-fips-adapter</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\itext.commons\itext.commons.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="bc-fips-1.0.2">
      <HintPath>lib\bc-fips\bc-fips-1.0.2.dll</HintPath>
    </Reference>
    <Reference Include="bcpkix-fips-1.0.2">
      <HintPath>lib\bc-fips\bcpkix-fips-1.0.2.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>