<Project>
    <PropertyGroup>
        <TargetFrameworks>net8.0;netcoreapp2.0;net461</TargetFrameworks>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(TargetFramework)' == 'net461' ">
        <OutputType>library</OutputType>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(TargetFramework)' != 'net461' ">
        <OutputType>Library</OutputType>
        <DefineConstants>NETSTANDARD2_0</DefineConstants>
    </PropertyGroup>

    <ItemGroup Condition=" '$(TargetFramework)' == 'net461'  ">
        <PackageReference Include="NUnit" Version="3.7.1"/>
        <PackageReference Include="NUnit3TestAdapter" Version="3.10.0"/>
        <PackageReference Include="Microsoft.CodeCoverage" Version="16.11.0"/>
        <Reference Include="System"/>
        <Reference Include="System.Core"/>
        <Reference Include="System.Xml" />
        <Reference Include="System.Xml.Linq" />
    </ItemGroup>



    <ItemGroup Condition="'$(TargetFramework)' == 'netcoreapp2.0'">
        <PackageReference Include="NUnit" Version="3.7.1"/>
        <PackageReference Include="NUnit3TestAdapter" Version="3.10.0"/>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0"/>
        <PackageReference Include="Microsoft.CodeCoverage" Version="16.11.0"/>
        <PackageReference Include="System.Runtime.InteropServices.RuntimeInformation" Version="4.3.0"/>
    </ItemGroup>


    <ItemGroup Condition=" '$(TargetFramework)' == 'net8.0' ">
        <PackageReference Include="NUnit" Version="3.14.0"/>
        <PackageReference Include="NUnit3TestAdapter" Version="4.6.0"/>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1"/>
    </ItemGroup>

</Project>

