<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="15.0">
  <!-- The .csrpoj file uses ../Directory.Build.props as a source for some configurations -->
  <PropertyGroup>
    <AssemblyName>itext.sign.tests</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="itext.eu-trusted-lists-resources" Version="1.1.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\itext\itext.forms\itext.forms.csproj" />
    <ProjectReference Include="..\..\itext\itext.pdftest\itext.pdftest.csproj" />
    <ProjectReference Include="..\..\itext\itext.sign\itext.sign.csproj" />
  </ItemGroup>
</Project>