<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="15.0">
  <!-- The .csrpoj file uses ../Directory.Build.props as a source for some configurations -->
  <PropertyGroup>
    <!-- TargetFrameworks property from ../Directory.Build.props is overriden -->
    <TargetFrameworks>netstandard2.1;net8.0</TargetFrameworks>
    <AssemblyName>itext.brotli-compressor</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\itext.commons\itext.commons.csproj" />
    <ProjectReference Include="..\itext.kernel\itext.kernel.csproj" />
  </ItemGroup>
</Project>