name: iText7 CI/CD Pipeline

on: [push, pull_request, workflow_dispatch]

jobs:
  ci:
    runs-on: windows-latest
    steps:
      - name: Setup MSBuild
        id: setup_msbuild
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Checkout repository
        id: checkout_repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Clean .NET cache
        id: clean_dotnet_cache
        shell: powershell
        run: |
          dotnet clean .\iTextCore.netstandard.sln -c Release 
          dotnet nuget locals all --clear

      - name: Install .NET dependencies
        id: install_dotnet_dependencies
        shell: powershell
        run: dotnet tool restore      

      - name: Build solution
        id: build_solution
        shell: pwsh
        run: |
          msbuild .\iTextCore.netstandard.sln

# Built with ❤ by [Pipeline Foundation](https://pipeline.foundation)